name: Generate Pinouts

on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rusefi/rusefi/.github/workflows/gen-pinouts-top-level.yaml@master
    permissions:
      contents: write
